language: node_js
node_js:
- '10'
dist: trusty
cache: 
  yarn: true
  directories:
    - node_modules
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
- npm install -g firebase-tools
script:
- yarn deploy --token $FIREBASE_TOKEN
