language: node_js
node_js:
- '10'
cache: yarn
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
- npm install -g firebase-tools
- npm install -g @angular/cli
script:
- yarn deploy --token $FIREBASE_TOKEN
env:
  global:
    secure: mD+zWojA/vMqXUwiB7DNBOp8Iq0siEBuUlrNzTdmhx0vaTfGxb5c2DQdZe4mVXDFLNpaNearvxfgREmsRCbeE858ccHV3miYA3/fHaW3tdjU0O8CVv0SlQQn2RI5/qss12j/xrEaOz3bHYtmsxGPzzRD4YzPnGKc0fSzAiHuHv3FIEjEQ1NzsEWGjEkJs/pFCk3SY6MEz5n45WoB9h71pJZgYFDse650XlhmP2txOaO0E3RLOvMum1B0kINmreRNgfTZTNrr08sj/LFrR9OmGnyQr5iMCaBz5fjym0h51Q8UuZkMZ1okiHj2w2w7KpYfU/AnVgdKcXeX1kCNdI33bQwnWoohSNHG3wnnNuClj/Q6HB1XWkBvn4FVLzC2OMMNuu+HsnNzd0WvNd4PvtEfUF1fhPXbL+abYhccbvqt8d76Ds2DVuuZnD2KBTSf6vEwX+V06S0ile1J5jHe88A3rO61r6iELrJxhXgm6pmK/Ode4quW4MZ8bldqCqcbBZO26y15DQt9prN1SvMjDzviD+9eCbfcySm6NMNwBczAqf3N3ZeV3sryUVSnM6pSJjJCDDbUIhJAvv+Gmo8ZhZL/yJ5CNejmSU6APehy3jODLDp9TIiLp9Ly3SzKw6xjVWd8fHENKE3Wxp89NbuKjxgus4ARkhqImeGV0tSnN03VJ64=
