language: node_js
node_js:
- '10'
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
- npm install -g @angular/cli
script:
- yarn build --prod
deploy:
  provider: firebase
  token:
    secure: KhM2JGkOiynRsXNvLLmNSYJk90j74WyJdH2pDfSq3/UigZZOBpvERngKIwPWlOHIvF8KM0lQJz7fFyH/I4iMxaX9yihh64zCE8sovG+DoCeq7JUj5udGPaSV7sNPjSKabvb1nCkKc93yNgJIYP8OODjrwOj2nevtQm1K4PdR2WrekPXgo0RlO1gaAiwTEtzlGFSbBJLqw2cbdJ0SL2naUJsBg4FnhBTqi4bhwyISIOc6MecnxJGR3OGA+jbZJ3LLGppki4LFG9fsPtE6ivyJCedvas6LguE3lMbHXVyqBiaOVgjO+1KLesqfS2jFETREVXD2rnf8ZzFOGa9rk4mgr0zLeKg3zS/BBrlbQ7De6xEn5hmPf24oiTXckk+y7cciffyeLRdLGufFXjD/EJ0hJCTW4m+ywxEP8L5ibelS600s3tuIIls1q/7XAmech4I2kjORz+Xw0YPF1Eus8fv9U10HtczMFuoP5Xd7jUflix7NT91unTM8d261eO8r99ormkd0XemNHIfLStZ2VeVpwT1336dQWgAF8k5G9S22L9pdo+FnyJoYB4a4XkCSkDgP1AImbowm4Fc3nZeDy2J3YyquiIquYWtNN3gwKlOdeB4wieImiemgj+DXz8a0ibKzOx5CtY9POO26HxM7w25OWk+dQTAk//8keOelJ2gd4ZQ=
