language: node_js
node_js:
- '10'
env:
  secure: osHoaGEeekFuIng8+Sxk5saatCV5annJrPGkOQ5Bl3tBczcT36QBViH3GEg88mLWUgwZJNO3gnoPtddHB2G86n3bBT3hT7/1Od/vSSCnPWJaYuQ0HIDtYQu/0RhxfUM+EYGiSOgBDKc3gScKr+IZFzKjoHErsy6Z5la5wSwi+rsULc2Sf5yp9F8Iw3+WBAJU/5sT2G4t33YICWSNtd0MgoNCIipK1JQd8E67wnqI+FePGApm1TSeJO5MhiymP16/BpArawehdo931/rOIHlYGcrKq6fC+w5uegUDzQlgMLkapd9VzLY2Pub2tkWHjcAOTte99T01ymsGAILyRsXcMGNYM5An3zu4P24ebPBP9mGduG2ZDrF60JMxNfgtTgTSN0dGJWSRcRQwDH6mxZqF+3v0O99DtafE60eTmW4VBt++g6ZvJeejPxy8eKmSguOpYpWwmsubauntfsUF09Ws51CQm2pJfawN4yt/8eJeXoAhxmR75lsv7uRTlsJv/m7TQyvuzkMO3hUsvwXXIph5snuifY2YllXzz9q67W/wGFRwsQkrFquomFZQGUX3qLpst4Hmq00RW1mHdwDo0fnxeL233WOUdZDWgHrH6AsJJ4z6J9/Itj2iaqMhMrZ1Cx/XiRI/CIXh1PRLrXKoatipX5in9uAIuiD3QmTXAW5dHv4=
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
- npm install -g firebase-tools
- npm install -g @angular/cli
script:
- yarn deploy --token $FIREBASE_TOKEN
