language: node_js
node_js:
- '10'
cache: yarn
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
- npm install -g firebase-tools
- npm install -g @angular/cli
script:
- yarn deploy --token $FIREBASE_TOKEN