language: node_js
node_js:
- '10'
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
- npm install -g @angular/cli
script:
- yarn build --prod
deploy:
  provider: firebase
  token:
    secure: "FxdEvLbFmrT5gxX/mNUSiWJuR5JA0XEI+TqwgwL92N4924MdDxjkS0w0NXM3+YopqCU/MbHxFOZKcIZrWp/9BVtHawj2SXIuMaCM+GqthEzCaicbSdR8y4/SIzYxv8X6I2PT0RpD2q7FDTOI3hOJd4VKJ0M+wRgvI6qUJl9NV8e2LqSRTMJG+7wmmBfccOwJjeHXZzFhjOo1F4S06fBrbxnlKX9Rk8HwdJWlXnKXVPlzOhDGeD/p39LaNwwEwg4MOXmu9P9F9B+SweRPEvep9v+6ybGcYQfbXfxW0AWnPNsuJuNE7dWmBiCDG42/LJSIF7zAo+J+ntpNqjsVLe9g93fYOaXJPHmHfKF/iJKh96VZwdcQW3JYL683E0jgMc4KPIhFVeSZgJBrjdYU5y1a/IJsn2A0WNB39xjtTcr8cyRjk6kqtTZ2UAWy+X2w53cHDGPr4SuhoDaa0f8IgsNzhOiyuWWNiy2GmUtYnPby1ByNT8uktAfZH4bVYHk5SMJzvvE0nIxO8YRSHZgAPnTVrlJwo5A7ZNs4DNP9QuBL4S1y4DmUeWYHVU3rbaEFVEBtTibkGZmlxWiKq3lWgT2XKLciA+fUX9vfXBCJ5M0VJCTBBqzMxfyOjF2YPjPxVIWwJ/YkrUC2KrKeWgbNl574fb+VSUAVL/7Y20m2ix/Fw9o="